name: Cross-Compile Cuberite for Termux (Android armv7)

on:
  workflow_dispatch:

jobs:
  build-android-armv7:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Cuberite with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download and setup Android NDK
        env:
          NDK_VERSION: 25.2.9519653
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          echo "$PWD/android-ndk-r25b" > $GITHUB_ENV

      - name: Set environment variables for NDK
        run: |
          echo "ANDROID_NDK_ROOT=$PWD/android-ndk-r25b" >> $GITHUB_ENV
          echo "PATH=$PWD/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_PATH

      - name: Configure Cuberite for Android ARMv7 (Termux)
        run: |
          export ANDROID_NDK_ROOT=$PWD/android-ndk-r25b
          export TOOLCHAIN=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET_HOST=armv7a-linux-androideabi
          export API=24

          export CC=$TOOLCHAIN/bin/${TARGET_HOST}${API}-clang
          export CXX=$TOOLCHAIN/bin/${TARGET_HOST}${API}-clang++

          mkdir -p build
          cd build

          cmake .. -G Ninja \
            -DCMAKE_SYSTEM_NAME=Android \
            -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a \
            -DCMAKE_ANDROID_NDK=$ANDROID_NDK_ROOT \
            -DCMAKE_ANDROID_STL_TYPE=c++_shared \
            -DCMAKE_SYSTEM_VERSION=$API \
            -DCMAKE_C_COMPILER=$CC \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
            -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
            -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY

      - name: Build Cuberite for Android ARMv7
        run: |
          cmake --build build --config Release -j$(nproc)

      - name: Strip and compress Cuberite binary
        run: |
          BIN="build/Server/Cuberite"
          if [ -f "$BIN" ]; then
            file "$BIN"
            $TOOLCHAIN/bin/arm-linux-androideabi-strip "$BIN" || echo "Strip failed"
            upx --best --lzma "$BIN" || echo "UPX compression failed"
          fi

      - name: Upload full Cuberite Server directory
        uses: actions/upload-artifact@v4
        with:
          name: cuberite-android-armv7
          path: build/Server/
