name: Cross-Compile Cuberite for ARMv7 (GCC, glibc)

on:
  workflow_dispatch:

jobs:
  build-armv7-gcc:
    name: ARMv7 (glibc) Static Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Cuberite with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            git \
            curl \
            wget \
            file \
            zip \
            python3 \
            gawk \
            bison \
            flex \
            texinfo \
            help2man \
            libtool \
            automake \
            autoconf \
            gcc-arm-linux-gnueabihf \
            g++-arm-linux-gnueabihf \
            upx

      - name: Configure Cuberite for ARMv7 (glibc) static build
        run: |
          export CC=arm-linux-gnueabihf-gcc
          export CXX=arm-linux-gnueabihf-g++

          mkdir build
          cd build

          cmake .. -G Ninja \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=armv7 \
            -DCMAKE_C_COMPILER=${CC} \
            -DCMAKE_CXX_COMPILER=${CXX} \
            -DCMAKE_FIND_ROOT_PATH=/usr/arm-linux-gnueabihf \
            -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
            -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
            -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXE_LINKER_FLAGS="-static" \
            -DCMAKE_CXX_FLAGS="--static -static-libstdc++ -static-libgcc" \
            -DCMAKE_C_FLAGS="--static -static-libgcc"

      - name: Build Cuberite for ARMv7
        run: |
          cmake --build build --config Release -j$(nproc)

      - name: List built contents
        run: |
          ls -lh build/Server || echo "No contents found in build/Server"

      - name: Strip and compress the Cuberite binary
        run: |
          BIN="build/Server/Cuberite"
          if [ -f "$BIN" ]; then
            file "$BIN"
            arm-linux-gnueabihf-strip "$BIN" || echo "Skipping strip for $BIN"
            upx --best --lzma "$BIN" || echo "UPX compression skipped for $BIN"
          fi

      - name: Upload full Cuberite Server folder
        uses: actions/upload-artifact@v4
        with:
          name: cuberite-armv7-gcc-static-server
          path: build/Server/
